# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "bento/ubuntu-20.04"
    config.disksize.size = '50GB'
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    config.vm.define "ubuntu-otus" do |ubuntu|
      ubuntu.vm.network "private_network", ip: "192.168.50.2", virtualbox__intnet: "net1"
      ubuntu.vm.hostname = "ubuntu-otus"
      ubuntu.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh;
        echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8fNI9IH4hjTnyKqPVUbg44rFrf9UGmFwJaWX+lYQEvGHOObiWtrn5k3/gomiV2LBv7P1bq+aga7k9qHQ+4ueXXnuvCzkFn6kIXYL2bnu5gqasIYv+ugtgRFBAELM+E4YL/TUbWgIWkZ6O5fFmO4yS7aRi1H8a9FpJixzCqVq0DqmGaspemsAxbK9tlktPr7PQToABJEPDcz2mc2D6tw3m1VZ8mMwsjLdOLQYijlf093kK4CSrasNkBC5YZxKsP+g67AGSDwLCkVcYRLi3R4a6FRHef9H9mRxIxO5r+ojMny/ZM0Gk9YmclSrPTLPTaqPCcTYRi92Kt8xUtGvxdFCF 1@konstantin_pk >> /root/.ssh/authorized_keys
      SHELL
    end
  end
  